#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
border_color="#84a4c4"
urgent_border_color="#84a4c4"

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 0 1 2 3 4
bspc config border_width         2
bspc config focused_border_color          $border_color
bspc config urgent_border_color          $urgent_border_color
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale /home/oswald/Pictures/Wallpapers/6.png &
picom --experimental-backend &
/home/oswald/.config/polybar/launch.sh &
